# Generated by Django 4.0.1 on 2022-06-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_rename_command_soundhistory_sound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soundhistory',
            old_name='played',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='sounds',
        ),
        migrations.AddField(
            model_name='sound',
            name='tags',
            field=models.ManyToManyField(to='frontend.Tag'),
        ),
        migrations.AlterField(
            model_name='soundhistory',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.sound'),
        ),
    ]
