version: '3'

services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    depends_on:
      - "db"
      - "rabbitmq"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - "website"
    volumes:
      - static:/static:ro
      - media:/media:ro

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - media:/app/media:ro
    depends_on:
      - "db"
      - "rabbitmq"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}

  rabbitmq:
    image: rabbitmq:3.9.13
    hostname: my-rabbit


volumes:
  static:
    external: true
  media:
    external: true
  db_data:
    external: true
